// <auto-generated/>
namespace FBITools
{
    partial class MainMenuForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.MainContentTable = new FBITools.FlatTableA();
            this.InputTable = new FBITools.FlatTableA();
            this.FileCopyTabButton = new FBITools.FlatButtonA();
            this.ImageResizeTabButton = new FBITools.FlatButtonA();
            this.VbCsharpTabButton = new FBITools.FlatButtonA();
            this.WiiUTabButton = new FBITools.FlatButtonA();
            this.ConfigTabButton = new FBITools.FlatButtonA();
            this.MainContentTable.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.SuspendLayout();
            // 
            // MainContentTable
            // 
            this.MainContentTable.ColumnCount = 1;
            this.MainContentTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Controls.Add(this.InputTable, 0, 0);
            this.MainContentTable.Controls.Add(this.ConfigTabButton, 0, 1);
            this.MainContentTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainContentTable.FillOnFormResize = true;
            this.MainContentTable.Location = new System.Drawing.Point(0, 0);
            this.MainContentTable.Name = "MainContentTable";
            this.MainContentTable.Padding = new System.Windows.Forms.Padding(1);
            this.MainContentTable.RowCount = 2;
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Size = new System.Drawing.Size(300, 189);
            this.MainContentTable.SizeOriginal = new System.Drawing.Size(300, 189);
            this.MainContentTable.TabIndex = 10;
            // 
            // InputTable
            // 
            this.InputTable.AutoSize = false;
            this.InputTable.ColumnCount = 2;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.InputTable.Controls.Add(this.FileCopyTabButton, 0, 0);
            this.InputTable.Controls.Add(this.ImageResizeTabButton, 0, 1);
            this.InputTable.Controls.Add(this.VbCsharpTabButton, 0, 2);
            this.InputTable.Controls.Add(this.WiiUTabButton, 0, 3);
            this.InputTable.Dock = System.Windows.Forms.DockStyle.None;
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "InputTable";
            this.InputTable.RowCount = 4;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.InputTable.Size = new System.Drawing.Size(298, 150);
            this.InputTable.SizeOriginal = new System.Drawing.Size(298, 150);
            this.InputTable.TabIndex = 0;
            // 
            // FileCopyTabButton
            // 
            this.FileCopyTabButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.InputTable.SetColumnSpan(this.FileCopyTabButton, 2);
            this.FileCopyTabButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.FileCopyTabButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.FileCopyTabButton.FlatAppearance.BorderSize = 0;
            this.FileCopyTabButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.FileCopyTabButton.Location = new System.Drawing.Point(0, 0);
            this.FileCopyTabButton.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.FileCopyTabButton.Name = "FileCopyTabButton";
            this.FileCopyTabButton.Size = new System.Drawing.Size(298, 34);
            this.FileCopyTabButton.TabIndex = 0;
            this.FileCopyTabButton.Text = "File Copy";
            // 
            // ImageResizeTabButton
            // 
            this.ImageResizeTabButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.InputTable.SetColumnSpan(this.ImageResizeTabButton, 2);
            this.ImageResizeTabButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ImageResizeTabButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ImageResizeTabButton.FlatAppearance.BorderSize = 0;
            this.ImageResizeTabButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ImageResizeTabButton.Location = new System.Drawing.Point(0, 38);
            this.ImageResizeTabButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.ImageResizeTabButton.Name = "ImageResizeTabButton";
            this.ImageResizeTabButton.Size = new System.Drawing.Size(298, 34);
            this.ImageResizeTabButton.TabIndex = 1;
            this.ImageResizeTabButton.Text = "Image Resize";
            // 
            // VbCsharpTabButton
            // 
            this.VbCsharpTabButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.InputTable.SetColumnSpan(this.VbCsharpTabButton, 2);
            this.VbCsharpTabButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.VbCsharpTabButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.VbCsharpTabButton.FlatAppearance.BorderSize = 0;
            this.VbCsharpTabButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.VbCsharpTabButton.Location = new System.Drawing.Point(0, 76);
            this.VbCsharpTabButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.VbCsharpTabButton.Name = "VbCsharpTabButton";
            this.VbCsharpTabButton.Size = new System.Drawing.Size(298, 34);
            this.VbCsharpTabButton.TabIndex = 2;
            this.VbCsharpTabButton.Text = "VB to CSharp";
            // 
            // WiiUTabButton
            // 
            this.WiiUTabButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.InputTable.SetColumnSpan(this.WiiUTabButton, 2);
            this.WiiUTabButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WiiUTabButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.WiiUTabButton.FlatAppearance.BorderSize = 0;
            this.WiiUTabButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.WiiUTabButton.Location = new System.Drawing.Point(0, 114);
            this.WiiUTabButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.WiiUTabButton.Name = "WiiUTabButton";
            this.WiiUTabButton.Size = new System.Drawing.Size(298, 34);
            this.WiiUTabButton.TabIndex = 3;
            this.WiiUTabButton.Text = "WiiU";
            // 
            // ConfigTabButton
            // 
            this.ConfigTabButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.MainContentTable.SetColumnSpan(this.ConfigTabButton, 2);
            this.ConfigTabButton.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.ConfigTabButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ConfigTabButton.FlatAppearance.BorderSize = 0;
            this.ConfigTabButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ConfigTabButton.Location = new System.Drawing.Point(1, 154);
            this.ConfigTabButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.ConfigTabButton.Name = "ConfigTabButton";
            this.ConfigTabButton.Size = new System.Drawing.Size(298, 34);
            this.ConfigTabButton.TabIndex = 1;
            this.ConfigTabButton.Text = "Config";
            // 
            // MainMenuForm
            // 
            this.AutoScroll = true;
            this.ClientSize = new System.Drawing.Size(300, 189);
            this.Controls.Add(this.MainContentTable);
            this.Name = "MainMenuForm";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "ConfigForm";
            this.MainContentTable.ResumeLayout(false);
            this.InputTable.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatTableA MainContentTable;
        private FlatTableA InputTable;
        internal FlatButtonA FileCopyTabButton;
        internal FlatButtonA ImageResizeTabButton;
        internal FlatButtonA VbCsharpTabButton;
        internal FlatButtonA WiiUTabButton;
        internal FlatButtonA ConfigTabButton;

    }
}