// <auto-generated/>
namespace FBITools
{
    partial class FileCopyForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.MainContentTable = new FBITools.FlatTableA();
            this.InputTable = new FBITools.FlatTableA();
            this.TitleLabel = new FBITools.FlatLabelA();
            this.OriginButton = new FBITools.FlatButtonA();
            this.OriginTextBox = new FBITools.FlatTextBoxA();
            this.DestinationButton = new FBITools.FlatButtonA();
            this.DestinationTextBox = new FBITools.FlatTextBoxA();
            this.CustomDestinationCheckBox = new FBITools.FlatCheckBoxA();
            this.TypeComboBox = new FBITools.FlatComboBoxA();
            this.TimerComboBox = new FBITools.FlatComboBoxA();
            this.ResultTable = new FBITools.FlatTableA();
            this.CopyButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.MainContentTable.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.ResultTable.SuspendLayout();
            this.SuspendLayout();
            // 
            // MainContentTable
            // 
            this.MainContentTable.ColumnCount = 1;
            this.MainContentTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Controls.Add(this.InputTable, 0, 0);
            this.MainContentTable.Controls.Add(this.ResultTable, 0, 1);
            this.MainContentTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainContentTable.FillOnFormResize = true;
            this.MainContentTable.Location = new System.Drawing.Point(0, 0);
            this.MainContentTable.Name = "MainContentTable";
            this.MainContentTable.Padding = new System.Windows.Forms.Padding(1);
            this.MainContentTable.RowCount = 3;
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Size = new System.Drawing.Size(430, 262);
            this.MainContentTable.SizeOriginal = new System.Drawing.Size(430, 262);
            this.MainContentTable.TabIndex = 0;
            // 
            // InputTable
            // 
            this.InputTable.ColumnCount = 2;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 102F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.InputTable.Controls.Add(this.TitleLabel, 0, 0);
            this.InputTable.Controls.Add(this.OriginButton, 0, 1);
            this.InputTable.Controls.Add(this.OriginTextBox, 1, 1);
            this.InputTable.Controls.Add(this.DestinationButton, 0, 2);
            this.InputTable.Controls.Add(this.DestinationTextBox, 1, 2);
            this.InputTable.Controls.Add(this.CustomDestinationCheckBox, 0, 3);
            this.InputTable.Controls.Add(this.TypeComboBox, 0, 4);
            this.InputTable.Controls.Add(this.TimerComboBox, 1, 4);
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "InputTable";
            this.InputTable.RowCount = 5;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.Size = new System.Drawing.Size(428, 186);
            this.InputTable.SizeOriginal = new System.Drawing.Size(428, 186);
            this.InputTable.TabIndex = 0;
            // 
            // TitleLabel
            // 
            this.InputTable.SetColumnSpan(this.TitleLabel, 2);
            this.TitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleLabel.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.TitleLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.TitleLabel.Location = new System.Drawing.Point(0, 0);
            this.TitleLabel.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.TitleLabel.Name = "TitleLabel";
            this.TitleLabel.Size = new System.Drawing.Size(428, 34);
            this.TitleLabel.TabIndex = 0;
            this.TitleLabel.Text = "File Copy";
            this.TitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // OriginButton
            // 
            this.OriginButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginButton.FlatAppearance.BorderSize = 0;
            this.OriginButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.OriginButton.Location = new System.Drawing.Point(0, 38);
            this.OriginButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.OriginButton.Name = "OriginButton";
            this.OriginButton.Size = new System.Drawing.Size(100, 34);
            this.OriginButton.TabIndex = 1;
            this.OriginButton.Text = "Origin";
            // 
            // OriginTextBox
            // 
            this.OriginTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.OriginTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.OriginTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginTextBox.Enabled = false;
            this.OriginTextBox.LabelText = "File";
            this.OriginTextBox.Location = new System.Drawing.Point(104, 38);
            this.OriginTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.OriginTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.OriginTextBox.Name = "OriginTextBox";
            this.OriginTextBox.PreviousText = "";
            this.OriginTextBox.ReadOnly = true;
            this.OriginTextBox.Size = new System.Drawing.Size(324, 34);
            this.OriginTextBox.TabIndex = 2;
            // 
            // DestinationButton
            // 
            this.DestinationButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationButton.FlatAppearance.BorderSize = 0;
            this.DestinationButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.DestinationButton.Location = new System.Drawing.Point(0, 76);
            this.DestinationButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.DestinationButton.Name = "DestinationButton";
            this.DestinationButton.Size = new System.Drawing.Size(100, 34);
            this.DestinationButton.TabIndex = 3;
            this.DestinationButton.Text = "Destination";
            // 
            // DestinationTextBox
            // 
            this.DestinationTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.DestinationTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.DestinationTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationTextBox.Enabled = false;
            this.DestinationTextBox.LabelText = "File";
            this.DestinationTextBox.Location = new System.Drawing.Point(104, 76);
            this.DestinationTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.DestinationTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.DestinationTextBox.Name = "DestinationTextBox";
            this.DestinationTextBox.PreviousText = "";
            this.DestinationTextBox.ReadOnly = true;
            this.DestinationTextBox.Size = new System.Drawing.Size(324, 34);
            this.DestinationTextBox.TabIndex = 4;
            // 
            // CustomDestinationCheckBox
            // 
            this.InputTable.SetColumnSpan(this.CustomDestinationCheckBox, 2);
            this.CustomDestinationCheckBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CustomDestinationCheckBox.Location = new System.Drawing.Point(0, 114);
            this.CustomDestinationCheckBox.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.CustomDestinationCheckBox.Name = "CustomDestinationCheckBox";
            this.CustomDestinationCheckBox.Size = new System.Drawing.Size(428, 34);
            this.CustomDestinationCheckBox.TabIndex = 5;
            this.CustomDestinationCheckBox.TextLegend = "Custom Destination";
            // 
            // TypeComboBox
            // 
            this.TypeComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.TypeComboBox.BackColor = System.Drawing.Color.White;
            this.TypeComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TypeComboBox.LabelText = "Type";
            this.TypeComboBox.Location = new System.Drawing.Point(0, 152);
            this.TypeComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 0);
            this.TypeComboBox.Name = "TypeComboBox";
            this.TypeComboBox.Size = new System.Drawing.Size(100, 34);
            this.TypeComboBox.TabIndex = 6;
            // 
            // TimerComboBox
            // 
            this.TimerComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.TimerComboBox.BackColor = System.Drawing.Color.White;
            this.TimerComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TimerComboBox.LabelText = "Timer";
            this.TimerComboBox.Location = new System.Drawing.Point(104, 152);
            this.TimerComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 0);
            this.TimerComboBox.Name = "TimerComboBox";
            this.TimerComboBox.Size = new System.Drawing.Size(324, 34);
            this.TimerComboBox.TabIndex = 7;
            // 
            // ResultTable
            // 
            this.ResultTable.ColumnCount = 1;
            this.ResultTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.Controls.Add(this.CopyButton, 0, 0);
            this.ResultTable.Controls.Add(this.WarningLabel, 0, 1);
            this.ResultTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResultTable.Location = new System.Drawing.Point(1, 187);
            this.ResultTable.Name = "ResultTable";
            this.ResultTable.RowCount = 3;
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.Size = new System.Drawing.Size(428, 66);
            this.ResultTable.SizeOriginal = new System.Drawing.Size(428, 66);
            this.ResultTable.TabIndex = 1;
            // 
            // CopyButton
            // 
            this.CopyButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CopyButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CopyButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CopyButton.FlatAppearance.BorderSize = 0;
            this.CopyButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.CopyButton.Location = new System.Drawing.Point(0, 4);
            this.CopyButton.Margin = new System.Windows.Forms.Padding(0, 4, 0, 2);
            this.CopyButton.Name = "CopyButton";
            this.CopyButton.Size = new System.Drawing.Size(428, 34);
            this.CopyButton.TabIndex = 0;
            this.CopyButton.Text = "Copy";
            // 
            // WarningLabel
            // 
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.Firebrick;
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.danger;
            this.WarningLabel.Location = new System.Drawing.Point(0, 42);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.WarningLabel.Name = "WarningLabel";
            this.WarningLabel.Size = new System.Drawing.Size(428, 24);
            this.WarningLabel.TabIndex = 1;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // FileCopyForm
            // 
            this.ClientSize = new System.Drawing.Size(430, 262);
            this.Controls.Add(this.MainContentTable);
            this.Name = "FileCopyForm";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "FileCopyForm";
            this.MainContentTable.ResumeLayout(false);
            this.MainContentTable.PerformLayout();
            this.InputTable.ResumeLayout(false);
            this.ResultTable.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatLabelA TitleLabel;
        internal FlatButtonA DestinationButton;
        internal FlatButtonA OriginButton;
        internal FlatTextBoxA OriginTextBox;
        internal FlatTextBoxA DestinationTextBox;
        internal FlatButtonA CopyButton;
        internal FlatLabelA WarningLabel;
        private FlatTableA MainContentTable;
        internal FlatComboBoxA TypeComboBox;
        internal FlatComboBoxA TimerComboBox;
        internal FlatTableA InputTable;
        private FlatTableA ResultTable;
        internal FlatCheckBoxA CustomDestinationCheckBox;
    }
}