// <auto-generated/>
namespace FBITools
{
    partial class ImageResizeForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.MainContentTable = new FBITools.FlatTableA();
            this.InputTable = new FBITools.FlatTableA();
            this.TitleLabel = new FBITools.FlatLabelA();
            this.OriginButton = new FBITools.FlatButtonA();
            this.OriginTextBox = new FBITools.FlatTextBoxA();
            this.DestinationButton = new FBITools.FlatButtonA();
            this.DestinationTextBox = new FBITools.FlatTextBoxA();
            this.EncoderComboBox = new FBITools.FlatComboBoxA();
            this.ResizeModeComboBox = new FBITools.FlatComboBoxA();
            this.SizesComboBox = new FBITools.FlatComboBoxA();
            this.AnchorComboBox = new FBITools.FlatComboBoxA();
            this.InterpolationComboBox = new FBITools.FlatComboBoxA();
            this.MatteColorComboBox = new FBITools.FlatComboBoxA();
            this.ColorProfileComboBox = new FBITools.FlatComboBoxA();
            this.SharpenComboBox = new FBITools.FlatComboBoxA();
            this.BlendingModeComboBox = new FBITools.FlatComboBoxA();
            this.HybridModeComboBox = new FBITools.FlatComboBoxA();
            this.PNGLabel = new FBITools.FlatLabelA();
            this.PngFilterComboBox = new FBITools.FlatComboBoxA();
            this.PngInterlaceComboBox = new FBITools.FlatComboBoxA();
            this.JPGLabel = new FBITools.FlatLabelA();
            this.JpgQualityComboBox = new FBITools.FlatComboBoxA();
            this.JpgChromaSubsampleComboBox = new FBITools.FlatComboBoxA();
            this.ResultTable = new FBITools.FlatTableA();
            this.ResizeButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.DropPictureBox = new FBITools.FlatPictureBoxA();
            this.ResizedPictureBox = new FBITools.FlatPictureBoxA();
            this.MainContentTable.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.ResultTable.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.DropPictureBox)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.ResizedPictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // MainContentTable
            // 
            this.MainContentTable.ColumnCount = 1;
            this.MainContentTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Controls.Add(this.InputTable, 0, 0);
            this.MainContentTable.Controls.Add(this.ResultTable, 0, 1);
            this.MainContentTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainContentTable.FillOnFormResize = true;
            this.MainContentTable.Location = new System.Drawing.Point(0, 0);
            this.MainContentTable.Name = "MainContentTable";
            this.MainContentTable.Padding = new System.Windows.Forms.Padding(1);
            this.MainContentTable.RowCount = 3;
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Size = new System.Drawing.Size(465, 656);
            this.MainContentTable.SizeOriginal = new System.Drawing.Size(465, 656);
            this.MainContentTable.TabIndex = 0;
            // 
            // InputTable
            // 
            this.InputTable.ColumnCount = 3;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 102F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.InputTable.Controls.Add(this.TitleLabel, 0, 0);
            this.InputTable.Controls.Add(this.OriginButton, 0, 1);
            this.InputTable.Controls.Add(this.OriginTextBox, 1, 1);
            this.InputTable.Controls.Add(this.DestinationButton, 0, 2);
            this.InputTable.Controls.Add(this.DestinationTextBox, 1, 2);
            this.InputTable.Controls.Add(this.EncoderComboBox, 0, 3);
            this.InputTable.Controls.Add(this.ResizeModeComboBox, 1, 3);
            this.InputTable.Controls.Add(this.SizesComboBox, 2, 3);
            this.InputTable.Controls.Add(this.AnchorComboBox, 0, 4);
            this.InputTable.Controls.Add(this.InterpolationComboBox, 2, 4);
            this.InputTable.Controls.Add(this.MatteColorComboBox, 0, 5);
            this.InputTable.Controls.Add(this.ColorProfileComboBox, 2, 5);
            this.InputTable.Controls.Add(this.SharpenComboBox, 0, 6);
            this.InputTable.Controls.Add(this.BlendingModeComboBox, 1, 6);
            this.InputTable.Controls.Add(this.HybridModeComboBox, 2, 6);
            this.InputTable.Controls.Add(this.PNGLabel, 0, 7);
            this.InputTable.Controls.Add(this.PngFilterComboBox, 1, 7);
            this.InputTable.Controls.Add(this.PngInterlaceComboBox, 2, 7);
            this.InputTable.Controls.Add(this.JPGLabel, 0, 8);
            this.InputTable.Controls.Add(this.JpgQualityComboBox, 1, 8);
            this.InputTable.Controls.Add(this.JpgChromaSubsampleComboBox, 2, 8);
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "InputTable";
            this.InputTable.RowCount = 9;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.Size = new System.Drawing.Size(463, 356);
            this.InputTable.SizeOriginal = new System.Drawing.Size(463, 356);
            this.InputTable.TabIndex = 0;
            // 
            // TitleLabel
            // 
            this.InputTable.SetColumnSpan(this.TitleLabel, 3);
            this.TitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleLabel.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.TitleLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.TitleLabel.Location = new System.Drawing.Point(0, 0);
            this.TitleLabel.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.TitleLabel.Name = "TitleLabel";
            this.TitleLabel.Size = new System.Drawing.Size(463, 34);
            this.TitleLabel.TabIndex = 0;
            this.TitleLabel.Text = "Image Resize";
            this.TitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // OriginButton
            // 
            this.OriginButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginButton.FlatAppearance.BorderSize = 0;
            this.OriginButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.OriginButton.Location = new System.Drawing.Point(0, 38);
            this.OriginButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.OriginButton.Name = "OriginButton";
            this.OriginButton.Size = new System.Drawing.Size(100, 34);
            this.OriginButton.TabIndex = 1;
            this.OriginButton.Text = "Origin";
            // 
            // OriginTextBox
            // 
            this.OriginTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.OriginTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.InputTable.SetColumnSpan(this.OriginTextBox, 2);
            this.OriginTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginTextBox.Enabled = false;
            this.OriginTextBox.LabelText = "File";
            this.OriginTextBox.Location = new System.Drawing.Point(104, 38);
            this.OriginTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.OriginTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.OriginTextBox.Name = "OriginTextBox";
            this.OriginTextBox.PreviousText = "";
            this.OriginTextBox.ReadOnly = true;
            this.OriginTextBox.Size = new System.Drawing.Size(359, 34);
            this.OriginTextBox.TabIndex = 2;
            // 
            // DestinationButton
            // 
            this.DestinationButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationButton.FlatAppearance.BorderSize = 0;
            this.DestinationButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.DestinationButton.Location = new System.Drawing.Point(0, 76);
            this.DestinationButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.DestinationButton.Name = "DestinationButton";
            this.DestinationButton.Size = new System.Drawing.Size(100, 34);
            this.DestinationButton.TabIndex = 3;
            this.DestinationButton.Text = "Destination";
            // 
            // DestinationTextBox
            // 
            this.DestinationTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.DestinationTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.InputTable.SetColumnSpan(this.DestinationTextBox, 2);
            this.DestinationTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationTextBox.Enabled = false;
            this.DestinationTextBox.LabelText = "File";
            this.DestinationTextBox.Location = new System.Drawing.Point(104, 76);
            this.DestinationTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.DestinationTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.DestinationTextBox.Name = "DestinationTextBox";
            this.DestinationTextBox.PreviousText = "";
            this.DestinationTextBox.ReadOnly = true;
            this.DestinationTextBox.Size = new System.Drawing.Size(359, 34);
            this.DestinationTextBox.TabIndex = 4;
            // 
            // EncoderComboBox
            // 
            this.EncoderComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.EncoderComboBox.BackColor = System.Drawing.Color.White;
            this.EncoderComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.EncoderComboBox.LabelText = "Encoder";
            this.EncoderComboBox.Location = new System.Drawing.Point(0, 114);
            this.EncoderComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.EncoderComboBox.Name = "EncoderComboBox";
            this.EncoderComboBox.Size = new System.Drawing.Size(100, 34);
            this.EncoderComboBox.TabIndex = 5;
            // 
            // ResizeModeComboBox
            // 
            this.ResizeModeComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ResizeModeComboBox.BackColor = System.Drawing.Color.White;
            this.ResizeModeComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResizeModeComboBox.LabelText = "ResizeMode";
            this.ResizeModeComboBox.Location = new System.Drawing.Point(104, 114);
            this.ResizeModeComboBox.Name = "ResizeModeComboBox";
            this.ResizeModeComboBox.Size = new System.Drawing.Size(176, 34);
            this.ResizeModeComboBox.TabIndex = 6;
            // 
            // SizesComboBox
            // 
            this.SizesComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.SizesComboBox.BackColor = System.Drawing.Color.White;
            this.SizesComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SizesComboBox.LabelText = "Size";
            this.SizesComboBox.Location = new System.Drawing.Point(284, 114);
            this.SizesComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.SizesComboBox.Name = "SizesComboBox";
            this.SizesComboBox.Size = new System.Drawing.Size(179, 34);
            this.SizesComboBox.TabIndex = 7;
            // 
            // AnchorComboBox
            // 
            this.AnchorComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.AnchorComboBox.BackColor = System.Drawing.Color.White;
            this.InputTable.SetColumnSpan(this.AnchorComboBox, 2);
            this.AnchorComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.AnchorComboBox.LabelText = "Anchor";
            this.AnchorComboBox.Location = new System.Drawing.Point(0, 152);
            this.AnchorComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.AnchorComboBox.Name = "AnchorComboBox";
            this.AnchorComboBox.Size = new System.Drawing.Size(280, 34);
            this.AnchorComboBox.TabIndex = 8;
            // 
            // InterpolationComboBox
            // 
            this.InterpolationComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.InterpolationComboBox.BackColor = System.Drawing.Color.White;
            this.InterpolationComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.InterpolationComboBox.LabelText = "Interpolation";
            this.InterpolationComboBox.Location = new System.Drawing.Point(284, 152);
            this.InterpolationComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.InterpolationComboBox.Name = "InterpolationComboBox";
            this.InterpolationComboBox.Size = new System.Drawing.Size(179, 34);
            this.InterpolationComboBox.TabIndex = 9;
            // 
            // MatteColorComboBox
            // 
            this.MatteColorComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.MatteColorComboBox.BackColor = System.Drawing.Color.White;
            this.InputTable.SetColumnSpan(this.MatteColorComboBox, 2);
            this.MatteColorComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MatteColorComboBox.LabelText = "MatteColor";
            this.MatteColorComboBox.Location = new System.Drawing.Point(0, 190);
            this.MatteColorComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.MatteColorComboBox.Name = "MatteColorComboBox";
            this.MatteColorComboBox.Size = new System.Drawing.Size(280, 34);
            this.MatteColorComboBox.TabIndex = 10;
            // 
            // ColorProfileComboBox
            // 
            this.ColorProfileComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ColorProfileComboBox.BackColor = System.Drawing.Color.White;
            this.ColorProfileComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ColorProfileComboBox.LabelText = "ColorProfile";
            this.ColorProfileComboBox.Location = new System.Drawing.Point(284, 190);
            this.ColorProfileComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.ColorProfileComboBox.Name = "ColorProfileComboBox";
            this.ColorProfileComboBox.Size = new System.Drawing.Size(179, 34);
            this.ColorProfileComboBox.TabIndex = 11;
            // 
            // SharpenComboBox
            // 
            this.SharpenComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.SharpenComboBox.BackColor = System.Drawing.Color.White;
            this.SharpenComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.SharpenComboBox.LabelText = "Sharpen";
            this.SharpenComboBox.Location = new System.Drawing.Point(0, 228);
            this.SharpenComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.SharpenComboBox.Name = "SharpenComboBox";
            this.SharpenComboBox.Size = new System.Drawing.Size(100, 34);
            this.SharpenComboBox.TabIndex = 12;
            // 
            // BlendingModeComboBox
            // 
            this.BlendingModeComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.BlendingModeComboBox.BackColor = System.Drawing.Color.White;
            this.BlendingModeComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.BlendingModeComboBox.LabelText = "BlendingMode";
            this.BlendingModeComboBox.Location = new System.Drawing.Point(104, 228);
            this.BlendingModeComboBox.Name = "BlendingModeComboBox";
            this.BlendingModeComboBox.Size = new System.Drawing.Size(176, 34);
            this.BlendingModeComboBox.TabIndex = 13;
            // 
            // HybridModeComboBox
            // 
            this.HybridModeComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.HybridModeComboBox.BackColor = System.Drawing.Color.White;
            this.HybridModeComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.HybridModeComboBox.LabelText = "HybridMode";
            this.HybridModeComboBox.Location = new System.Drawing.Point(284, 228);
            this.HybridModeComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.HybridModeComboBox.Name = "HybridModeComboBox";
            this.HybridModeComboBox.Size = new System.Drawing.Size(179, 34);
            this.HybridModeComboBox.TabIndex = 14;
            // 
            // PNGLabel
            // 
            this.PNGLabel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.PNGLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PNGLabel.Location = new System.Drawing.Point(0, 284);
            this.PNGLabel.Margin = new System.Windows.Forms.Padding(0, 20, 2, 2);
            this.PNGLabel.Name = "PNGLabel";
            this.PNGLabel.Size = new System.Drawing.Size(100, 34);
            this.PNGLabel.TabIndex = 15;
            this.PNGLabel.Text = "Png";
            this.PNGLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // PngFilterComboBox
            // 
            this.PngFilterComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.PngFilterComboBox.BackColor = System.Drawing.Color.White;
            this.PngFilterComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PngFilterComboBox.LabelText = "Filter";
            this.PngFilterComboBox.Location = new System.Drawing.Point(104, 284);
            this.PngFilterComboBox.Margin = new System.Windows.Forms.Padding(2, 20, 2, 2);
            this.PngFilterComboBox.Name = "PngFilterComboBox";
            this.PngFilterComboBox.Size = new System.Drawing.Size(176, 34);
            this.PngFilterComboBox.TabIndex = 16;
            // 
            // PngInterlaceComboBox
            // 
            this.PngInterlaceComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.PngInterlaceComboBox.BackColor = System.Drawing.Color.White;
            this.PngInterlaceComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PngInterlaceComboBox.LabelText = "Interlace";
            this.PngInterlaceComboBox.Location = new System.Drawing.Point(284, 284);
            this.PngInterlaceComboBox.Margin = new System.Windows.Forms.Padding(2, 20, 0, 2);
            this.PngInterlaceComboBox.Name = "PngInterlaceComboBox";
            this.PngInterlaceComboBox.Size = new System.Drawing.Size(179, 34);
            this.PngInterlaceComboBox.TabIndex = 17;
            // 
            // JPGLabel
            // 
            this.JPGLabel.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.JPGLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.JPGLabel.Location = new System.Drawing.Point(0, 322);
            this.JPGLabel.Margin = new System.Windows.Forms.Padding(0, 2, 2, 0);
            this.JPGLabel.Name = "JPGLabel";
            this.JPGLabel.Size = new System.Drawing.Size(100, 34);
            this.JPGLabel.TabIndex = 18;
            this.JPGLabel.Text = "Jpg";
            this.JPGLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // JpgQualityComboBox
            // 
            this.JpgQualityComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.JpgQualityComboBox.BackColor = System.Drawing.Color.White;
            this.JpgQualityComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.JpgQualityComboBox.LabelText = "Quality";
            this.JpgQualityComboBox.Location = new System.Drawing.Point(104, 322);
            this.JpgQualityComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 2, 0);
            this.JpgQualityComboBox.Name = "JpgQualityComboBox";
            this.JpgQualityComboBox.Size = new System.Drawing.Size(176, 34);
            this.JpgQualityComboBox.TabIndex = 19;
            // 
            // JpgChromaSubsampleComboBox
            // 
            this.JpgChromaSubsampleComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.JpgChromaSubsampleComboBox.BackColor = System.Drawing.Color.White;
            this.JpgChromaSubsampleComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.JpgChromaSubsampleComboBox.LabelText = "ChromaSubsample";
            this.JpgChromaSubsampleComboBox.Location = new System.Drawing.Point(284, 322);
            this.JpgChromaSubsampleComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 0);
            this.JpgChromaSubsampleComboBox.Name = "JpgChromaSubsampleComboBox";
            this.JpgChromaSubsampleComboBox.Size = new System.Drawing.Size(179, 34);
            this.JpgChromaSubsampleComboBox.TabIndex = 20;
            // 
            // ResultTable
            // 
            this.ResultTable.ColumnCount = 2;
            this.ResultTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ResultTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.ResultTable.Controls.Add(this.ResizeButton, 0, 0);
            this.ResultTable.Controls.Add(this.WarningLabel, 0, 1);
            this.ResultTable.Controls.Add(this.DropPictureBox, 0, 2);
            this.ResultTable.Controls.Add(this.ResizedPictureBox, 1, 2);
            this.ResultTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResultTable.Location = new System.Drawing.Point(1, 357);
            this.ResultTable.Name = "ResultTable";
            this.ResultTable.RowCount = 4;
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.Size = new System.Drawing.Size(463, 278);
            this.ResultTable.SizeOriginal = new System.Drawing.Size(463, 278);
            this.ResultTable.TabIndex = 1;
            // 
            // ResizeButton
            // 
            this.ResizeButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ResultTable.SetColumnSpan(this.ResizeButton, 2);
            this.ResizeButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResizeButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ResizeButton.FlatAppearance.BorderSize = 0;
            this.ResizeButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ResizeButton.Location = new System.Drawing.Point(0, 4);
            this.ResizeButton.Margin = new System.Windows.Forms.Padding(0, 4, 0, 2);
            this.ResizeButton.Name = "ResizeButton";
            this.ResizeButton.Size = new System.Drawing.Size(463, 34);
            this.ResizeButton.TabIndex = 0;
            this.ResizeButton.Text = "Resize";
            // 
            // WarningLabel
            // 
            this.ResultTable.SetColumnSpan(this.WarningLabel, 2);
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.Firebrick;
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.danger;
            this.WarningLabel.Location = new System.Drawing.Point(0, 42);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.WarningLabel.Name = "WarningLabel";
            this.WarningLabel.Size = new System.Drawing.Size(463, 24);
            this.WarningLabel.TabIndex = 1;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // DropPictureBox
            // 
            this.DropPictureBox.AllowDrop = true;
            this.DropPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.DropPictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DropPictureBox.Filter = ((App.Core.ImageFormats)(((App.Core.ImageFormats.Jpg | App.Core.ImageFormats.Jpeg) 
            | App.Core.ImageFormats.Png)));
            this.DropPictureBox.Image = null;
            this.DropPictureBox.Location = new System.Drawing.Point(0, 70);
            this.DropPictureBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 0);
            this.DropPictureBox.Name = "DropPictureBox";
            this.DropPictureBox.Size = new System.Drawing.Size(229, 208);
            this.DropPictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.DropPictureBox.TabIndex = 2;
            this.DropPictureBox.TabStop = false;
            // 
            // ResizedPictureBox
            // 
            this.ResizedPictureBox.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.ResizedPictureBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResizedPictureBox.Filter = ((App.Core.ImageFormats)(((App.Core.ImageFormats.Jpg | App.Core.ImageFormats.Jpeg) 
            | App.Core.ImageFormats.Png)));
            this.ResizedPictureBox.Image = null;
            this.ResizedPictureBox.Location = new System.Drawing.Point(233, 70);
            this.ResizedPictureBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 0);
            this.ResizedPictureBox.Name = "ResizedPictureBox";
            this.ResizedPictureBox.Size = new System.Drawing.Size(230, 208);
            this.ResizedPictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.ResizedPictureBox.TabIndex = 3;
            this.ResizedPictureBox.TabStop = false;
            // 
            // ImageResizeForm
            // 
            this.AllowDrop = true;
            this.ClientSize = new System.Drawing.Size(465, 656);
            this.Controls.Add(this.MainContentTable);
            this.Name = "ImageResizeForm";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "ImageResizeForm";
            this.MainContentTable.ResumeLayout(false);
            this.MainContentTable.PerformLayout();
            this.InputTable.ResumeLayout(false);
            this.ResultTable.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.DropPictureBox)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.ResizedPictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        internal FlatButtonA DestinationButton;
        internal FlatButtonA OriginButton;
        internal FlatTextBoxA OriginTextBox;
        internal FlatTextBoxA DestinationTextBox;
        internal FlatButtonA ResizeButton;
        internal FlatLabelA WarningLabel;
        private FlatTableA MainContentTable;
        private FlatTableA ResultTable;
        internal FlatPictureBoxA DropPictureBox;
        internal FlatPictureBoxA ResizedPictureBox;
        internal FlatComboBoxA SizesComboBox;
        private FlatLabelA TitleLabel;
        internal FlatComboBoxA EncoderComboBox;
        internal FlatComboBoxA ResizeModeComboBox;
        internal FlatComboBoxA InterpolationComboBox;
        internal FlatComboBoxA ColorProfileComboBox;
        internal FlatComboBoxA AnchorComboBox;
        internal FlatComboBoxA MatteColorComboBox;
        internal FlatComboBoxA SharpenComboBox;
        internal FlatComboBoxA BlendingModeComboBox;
        internal FlatComboBoxA HybridModeComboBox;
        internal FlatComboBoxA PngFilterComboBox;
        internal FlatComboBoxA PngInterlaceComboBox;
        private FlatLabelA PNGLabel;
        private FlatLabelA JPGLabel;
        internal FlatComboBoxA JpgQualityComboBox;
        internal FlatComboBoxA JpgChromaSubsampleComboBox;
        private FlatTableA InputTable;
    }
}