// <auto-generated/>
namespace FBITools
{
    partial class MainContentForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.ContentRPanel = new FBITools.FlatPanelA();
            this.ContentRInsidePanel = new FBITools.FlatPanelA();
            this.ContentLPanel = new FBITools.FlatPanelA();
            this.ContentLInsidePanel = new FBITools.FlatPanelA();
            this.ContentRPanel.SuspendLayout();
            this.ContentLPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // ContentRPanel
            // 
            this.ContentRPanel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(252)))), ((int)(((byte)(252)))));
            this.ContentRPanel.BackColorType = App.Core.Desktop.PanelType.white;
            this.ContentRPanel.Controls.Add(this.ContentRInsidePanel);
            this.ContentRPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ContentRPanel.Location = new System.Drawing.Point(146, 0);
            this.ContentRPanel.Name = "ContentRPanel";
            this.ContentRPanel.Padding = new System.Windows.Forms.Padding(4, 0, 0, 0);
            this.ContentRPanel.Size = new System.Drawing.Size(284, 262);
            this.ContentRPanel.TabIndex = 3;
            // 
            // ContentRInsidePanel
            // 
            this.ContentRInsidePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ContentRInsidePanel.Location = new System.Drawing.Point(4, 0);
            this.ContentRInsidePanel.Name = "ContentRInsidePanel";
            this.ContentRInsidePanel.Size = new System.Drawing.Size(280, 262);
            // 
            // ContentLPanel
            // 
            this.ContentLPanel.Controls.Add(this.ContentLInsidePanel);
            this.ContentLPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.ContentLPanel.Location = new System.Drawing.Point(0, 0);
            this.ContentLPanel.Name = "ContentLPanel";
            this.ContentLPanel.Size = new System.Drawing.Size(146, 262);
            this.ContentLPanel.TabIndex = 2;
            // 
            // ContentLInsidePanel
            // 
            this.ContentLInsidePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ContentLInsidePanel.Location = new System.Drawing.Point(0, 0);
            this.ContentLInsidePanel.Name = "ContentLInsidePanel";
            this.ContentLInsidePanel.Size = new System.Drawing.Size(146, 262);
            this.ContentLInsidePanel.TabIndex = 6;
            // 
            // MainContentForm
            // 
            this.ClientSize = new System.Drawing.Size(430, 262);
            this.Controls.Add(this.ContentRPanel);
            this.Controls.Add(this.ContentLPanel);
            this.Name = "MainContentForm";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "MainContentForm";
            this.ContentRPanel.ResumeLayout(false);
            this.ContentLPanel.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        internal FlatPanelA ContentLPanel;
        internal FlatPanelA ContentRPanel;
        internal FlatPanelA ContentRInsidePanel;
        internal FlatPanelA ContentLInsidePanel;
    }
}