// <auto-generated/>
namespace FBITools
{
    partial class VbToCsharpForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.MainContentTable = new FBITools.FlatTableLayoutPanelA();
            this.InputTable = new FBITools.FlatTableLayoutPanelA();
            this.TitleLabel = new FBITools.FlatLabelA();
            this.InputTextBox = new FBITools.FlatTextBoxA();
            this.ConvertButton = new FBITools.FlatButtonA();
            this.CopyResultButton = new FBITools.FlatButtonA();
            this.ClearButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.ResultTable = new FBITools.FlatTableLayoutPanelA();
            this.OutputTextBox = new FBITools.FlatTextBoxA();
            this.MainContentTable.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.ResultTable.SuspendLayout();
            this.SuspendLayout();
            // 
            // MainContentTable
            // 
            this.MainContentTable.ColumnCount = 1;
            this.MainContentTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Controls.Add(this.InputTable, 0, 0);
            this.MainContentTable.Controls.Add(this.ResultTable, 0, 1);
            this.MainContentTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainContentTable.FillOnFormResize = true;
            this.MainContentTable.Location = new System.Drawing.Point(0, 0);
            this.MainContentTable.Name = "MainContentTable";
            this.MainContentTable.Padding = new System.Windows.Forms.Padding(1);
            this.MainContentTable.RowCount = 2;
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.MainContentTable.Size = new System.Drawing.Size(834, 494);
            this.MainContentTable.SizeOriginal = new System.Drawing.Size(834, 494);
            this.MainContentTable.TabIndex = 0;
            // 
            // InputTable
            // 
            this.InputTable.ColumnCount = 3;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 34F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33F));
            this.InputTable.Controls.Add(this.TitleLabel, 0, 0);
            this.InputTable.Controls.Add(this.InputTextBox, 0, 1);
            this.InputTable.Controls.Add(this.ConvertButton, 0, 2);
            this.InputTable.Controls.Add(this.CopyResultButton, 1, 2);
            this.InputTable.Controls.Add(this.ClearButton, 2, 2);
            this.InputTable.Controls.Add(this.WarningLabel, 0, 3);
            this.InputTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "InputTable";
            this.InputTable.RowCount = 4;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.Size = new System.Drawing.Size(832, 221);
            this.InputTable.SizeOriginal = new System.Drawing.Size(832, 221);
            this.InputTable.TabIndex = 0;
            // 
            // TitleLabel
            // 
            this.InputTable.SetColumnSpan(this.TitleLabel, 3);
            this.TitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleLabel.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.TitleLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.TitleLabel.Location = new System.Drawing.Point(0, 0);
            this.TitleLabel.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.TitleLabel.Name = "TitleLabel";
            this.TitleLabel.Size = new System.Drawing.Size(832, 34);
            this.TitleLabel.TabIndex = 0;
            this.TitleLabel.Text = "VB.NET To CSharp";
            this.TitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // InputTextBox
            // 
            this.InputTable.SetColumnSpan(this.InputTextBox, 3);
            this.InputTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.InputTextBox.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.InputTextBox.LabelText = "Input";
            this.InputTextBox.Location = new System.Drawing.Point(0, 38);
            this.InputTextBox.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.InputTextBox.MaximumSize = new System.Drawing.Size(0, 0);
            this.InputTextBox.MaxLength = 0;
            this.InputTextBox.Multiline = true;
            this.InputTextBox.Name = "InputTextBox";
            this.InputTextBox.PreviousText = "";
            this.InputTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.InputTextBox.Size = new System.Drawing.Size(832, 115);
            this.InputTextBox.TabIndex = 1;
            // 
            // ConvertButton
            // 
            this.ConvertButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ConvertButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ConvertButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ConvertButton.FlatAppearance.BorderSize = 0;
            this.ConvertButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ConvertButton.Location = new System.Drawing.Point(0, 159);
            this.ConvertButton.Margin = new System.Windows.Forms.Padding(0, 4, 2, 2);
            this.ConvertButton.Name = "ConvertButton";
            this.ConvertButton.Size = new System.Drawing.Size(272, 34);
            this.ConvertButton.TabIndex = 2;
            this.ConvertButton.Text = "Convert";
            // 
            // CopyResultButton
            // 
            this.CopyResultButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CopyResultButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CopyResultButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CopyResultButton.FlatAppearance.BorderSize = 0;
            this.CopyResultButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.CopyResultButton.Location = new System.Drawing.Point(276, 159);
            this.CopyResultButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 2);
            this.CopyResultButton.Name = "CopyResultButton";
            this.CopyResultButton.Size = new System.Drawing.Size(278, 34);
            this.CopyResultButton.TabIndex = 3;
            this.CopyResultButton.Text = "Copy Result";
            // 
            // ClearButton
            // 
            this.ClearButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ClearButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ClearButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.ClearButton.FlatAppearance.BorderSize = 0;
            this.ClearButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.ClearButton.Location = new System.Drawing.Point(558, 159);
            this.ClearButton.Margin = new System.Windows.Forms.Padding(2, 4, 0, 2);
            this.ClearButton.Name = "ClearButton";
            this.ClearButton.Size = new System.Drawing.Size(274, 34);
            this.ClearButton.TabIndex = 4;
            this.ClearButton.Text = "Clear";
            // 
            // WarningLabel
            // 
            this.InputTable.SetColumnSpan(this.WarningLabel, 3);
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.WarningLabel.Location = new System.Drawing.Point(0, 197);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.WarningLabel.Name = "WarningLabel";
            this.WarningLabel.Size = new System.Drawing.Size(832, 24);
            this.WarningLabel.TabIndex = 5;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // ResultTable
            // 
            this.ResultTable.ColumnCount = 1;
            this.ResultTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.Controls.Add(this.OutputTextBox, 0, 0);
            this.ResultTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResultTable.Location = new System.Drawing.Point(1, 222);
            this.ResultTable.Name = "ResultTable";
            this.ResultTable.RowCount = 1;
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.ResultTable.Size = new System.Drawing.Size(832, 271);
            this.ResultTable.SizeOriginal = new System.Drawing.Size(832, 271);
            this.ResultTable.TabIndex = 1;
            // 
            // OutputTextBox
            // 
            this.OutputTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OutputTextBox.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OutputTextBox.LabelText = "Output";
            this.OutputTextBox.Location = new System.Drawing.Point(0, 2);
            this.OutputTextBox.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.OutputTextBox.MaximumSize = new System.Drawing.Size(0, 0);
            this.OutputTextBox.MaxLength = 0;
            this.OutputTextBox.Multiline = true;
            this.OutputTextBox.Name = "OutputTextBox";
            this.OutputTextBox.PreviousText = "";
            this.OutputTextBox.ReadOnly = true;
            this.OutputTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.OutputTextBox.Size = new System.Drawing.Size(832, 269);
            this.OutputTextBox.TabIndex = 0;
            // 
            // VbToCsharpForm
            // 
            this.ClientSize = new System.Drawing.Size(834, 494);
            this.Controls.Add(this.MainContentTable);
            this.Name = "VbToCsharpForm";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "VbToCsharpForm";
            this.MainContentTable.ResumeLayout(false);
            this.MainContentTable.PerformLayout();
            this.InputTable.ResumeLayout(false);
            this.ResultTable.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatLabelA TitleLabel;
        internal FlatTextBoxA InputTextBox;
        private FlatTableLayoutPanelA MainContentTable;
        internal FlatButtonA ConvertButton;
        internal FlatLabelA WarningLabel;
        private FlatTableLayoutPanelA ResultTable;
        internal FlatButtonA CopyResultButton;
        internal FlatButtonA ClearButton;
        internal FlatTextBoxA OutputTextBox;
        private FlatTableLayoutPanelA InputTable;
    }
}