// <auto-generated/>
namespace FBITools
{
    partial class FileCopyForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tblMainContent = new FBITools.FlatTableLayoutPanelA();
            this.InputTable = new FBITools.FlatTableLayoutPanelA();
            this.lblTitle = new FBITools.FlatLabelA();
            this.OriginButton = new FBITools.FlatButtonA();
            this.OriginTextBox = new FBITools.FlatTextBoxA();
            this.DestinationButton = new FBITools.FlatButtonA();
            this.DestinationTextBox = new FBITools.FlatTextBoxA();
            this.TypeComboBox = new FBITools.FlatComboBoxA();
            this.TimerComboBox = new FBITools.FlatComboBoxA();
            this.tblResult = new FBITools.FlatTableLayoutPanelA();
            this.CopyButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.tblMainContent.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.tblResult.SuspendLayout();
            this.SuspendLayout();
            // 
            // tblMainContent
            // 
            this.tblMainContent.ColumnCount = 1;
            this.tblMainContent.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblMainContent.Controls.Add(this.InputTable, 0, 0);
            this.tblMainContent.Controls.Add(this.tblResult, 0, 1);
            this.tblMainContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblMainContent.FillOnFormResize = true;
            this.tblMainContent.Location = new System.Drawing.Point(0, 0);
            this.tblMainContent.Name = "tblMainContent";
            this.tblMainContent.Padding = new System.Windows.Forms.Padding(1);
            this.tblMainContent.RowCount = 3;
            this.tblMainContent.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblMainContent.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblMainContent.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblMainContent.Size = new System.Drawing.Size(430, 262);
            this.tblMainContent.SizeOriginal = new System.Drawing.Size(430, 262);
            this.tblMainContent.TabIndex = 0;
            // 
            // tblInput
            // 
            this.InputTable.ColumnCount = 2;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 102F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.InputTable.Controls.Add(this.lblTitle, 0, 0);
            this.InputTable.Controls.Add(this.OriginButton, 0, 1);
            this.InputTable.Controls.Add(this.OriginTextBox, 1, 1);
            this.InputTable.Controls.Add(this.DestinationButton, 0, 2);
            this.InputTable.Controls.Add(this.DestinationTextBox, 1, 2);
            this.InputTable.Controls.Add(this.TypeComboBox, 0, 3);
            this.InputTable.Controls.Add(this.TimerComboBox, 1, 3);
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "tblInput";
            this.InputTable.RowCount = 4;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.Size = new System.Drawing.Size(428, 148);
            this.InputTable.SizeOriginal = new System.Drawing.Size(428, 148);
            this.InputTable.TabIndex = 0;
            // 
            // lblTitle
            // 
            this.InputTable.SetColumnSpan(this.lblTitle, 2);
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.lblTitle.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(428, 34);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "File Copy";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnOrigin
            // 
            this.OriginButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginButton.FlatAppearance.BorderSize = 0;
            this.OriginButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.OriginButton.Location = new System.Drawing.Point(0, 38);
            this.OriginButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.OriginButton.Name = "btnOrigin";
            this.OriginButton.Size = new System.Drawing.Size(100, 34);
            this.OriginButton.TabIndex = 1;
            this.OriginButton.Text = "Origin";
            // 
            // txtOrigin
            // 
            this.OriginTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.OriginTextBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.OriginTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.OriginTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.OriginTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.OriginTextBox.Enabled = false;
            this.OriginTextBox.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.OriginTextBox.LabelText = "File";
            this.OriginTextBox.Location = new System.Drawing.Point(104, 38);
            this.OriginTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.OriginTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.OriginTextBox.Name = "txtOrigin";
            this.OriginTextBox.Padding = new System.Windows.Forms.Padding(1);
            this.OriginTextBox.PreviousText = "";
            this.OriginTextBox.ReadOnly = true;
            this.OriginTextBox.Size = new System.Drawing.Size(324, 34);
            this.OriginTextBox.TabIndex = 2;
            // 
            // btnDestination
            // 
            this.DestinationButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationButton.FlatAppearance.BorderSize = 0;
            this.DestinationButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.DestinationButton.Location = new System.Drawing.Point(0, 76);
            this.DestinationButton.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.DestinationButton.Name = "btnDestination";
            this.DestinationButton.Size = new System.Drawing.Size(100, 34);
            this.DestinationButton.TabIndex = 3;
            this.DestinationButton.Text = "Destination";
            // 
            // txtDestination
            // 
            this.DestinationTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.DestinationTextBox.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.DestinationTextBox.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.DestinationTextBox.BackgroundColorFocus = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.DestinationTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DestinationTextBox.Enabled = false;
            this.DestinationTextBox.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.DestinationTextBox.LabelText = "File";
            this.DestinationTextBox.Location = new System.Drawing.Point(104, 76);
            this.DestinationTextBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.DestinationTextBox.MaximumSize = new System.Drawing.Size(0, 34);
            this.DestinationTextBox.Name = "txtDestination";
            this.DestinationTextBox.Padding = new System.Windows.Forms.Padding(1);
            this.DestinationTextBox.PreviousText = "";
            this.DestinationTextBox.ReadOnly = true;
            this.DestinationTextBox.Size = new System.Drawing.Size(324, 34);
            this.DestinationTextBox.TabIndex = 4;
            // 
            // cboType
            // 
            this.TypeComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.TypeComboBox.BackColor = System.Drawing.Color.White;
            this.TypeComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TypeComboBox.LabelText = "Type";
            this.TypeComboBox.Location = new System.Drawing.Point(0, 114);
            this.TypeComboBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 0);
            this.TypeComboBox.Name = "cboType";
            this.TypeComboBox.Size = new System.Drawing.Size(100, 34);
            this.TypeComboBox.TabIndex = 5;
            // 
            // cboTimer
            // 
            this.TimerComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.TimerComboBox.BackColor = System.Drawing.Color.White;
            this.TimerComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TimerComboBox.LabelText = "Timer";
            this.TimerComboBox.Location = new System.Drawing.Point(104, 114);
            this.TimerComboBox.Margin = new System.Windows.Forms.Padding(2, 2, 0, 0);
            this.TimerComboBox.Name = "cboTimer";
            this.TimerComboBox.Size = new System.Drawing.Size(324, 34);
            this.TimerComboBox.TabIndex = 6;
            // 
            // tblResult
            // 
            this.tblResult.ColumnCount = 1;
            this.tblResult.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblResult.Controls.Add(this.CopyButton, 0, 0);
            this.tblResult.Controls.Add(this.WarningLabel, 0, 1);
            this.tblResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblResult.Location = new System.Drawing.Point(1, 149);
            this.tblResult.Name = "tblResult";
            this.tblResult.RowCount = 3;
            this.tblResult.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblResult.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblResult.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblResult.Size = new System.Drawing.Size(428, 66);
            this.tblResult.SizeOriginal = new System.Drawing.Size(428, 66);
            this.tblResult.TabIndex = 1;
            // 
            // btnCopy
            // 
            this.CopyButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CopyButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CopyButton.FlatAppearance.BorderSize = 0;
            this.CopyButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.CopyButton.Location = new System.Drawing.Point(0, 4);
            this.CopyButton.Margin = new System.Windows.Forms.Padding(0, 4, 0, 2);
            this.CopyButton.Name = "btnCopy";
            this.CopyButton.Size = new System.Drawing.Size(428, 34);
            this.CopyButton.TabIndex = 0;
            this.CopyButton.Text = "Copy";
            // 
            // lblWarning
            // 
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.Firebrick;
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.danger;
            this.WarningLabel.Location = new System.Drawing.Point(0, 42);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.WarningLabel.Name = "lblWarning";
            this.WarningLabel.Size = new System.Drawing.Size(428, 24);
            this.WarningLabel.TabIndex = 1;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // FileCopyForm
            // 
            this.ClientSize = new System.Drawing.Size(430, 262);
            this.Controls.Add(this.tblMainContent);
            this.Name = "FileCopyForm";
            this.Text = "FileCopyForm";
            this.tblMainContent.ResumeLayout(false);
            this.tblMainContent.PerformLayout();
            this.InputTable.ResumeLayout(false);
            this.tblResult.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatLabelA lblTitle;
        internal FlatButtonA DestinationButton;
        internal FlatButtonA OriginButton;
        internal FlatTextBoxA OriginTextBox;
        internal FlatTextBoxA DestinationTextBox;
        internal FlatButtonA CopyButton;
        internal FlatLabelA WarningLabel;
        private FlatTableLayoutPanelA tblMainContent;
        internal FlatComboBoxA TypeComboBox;
        internal FlatComboBoxA TimerComboBox;
        internal FlatTableLayoutPanelA InputTable;
        private FlatTableLayoutPanelA tblResult;
    }
}