// <auto-generated/>
namespace FBITools
{
    partial class WiiUcetkForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.tblMainContent = new FBITools.FlatTableLayoutPanelA();
            this.tblInput = new FBITools.FlatTableLayoutPanelA();
            this.lblTitle = new FBITools.FlatLabelA();
            this.TitleIDTextBox = new FBITools.FlatMaskedTextBoxA();
            this.txtTitleName = new FBITools.FlatTextBoxA();
            this.ListRegionCheckedList = new FBITools.FlatCheckedListA();
            this.ListCategoryCheckedList = new FBITools.FlatCheckedListA();
            this.GenerateCetkButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.tblResult = new FBITools.FlatTableLayoutPanelA();
            this.TitlesGrid = new FBITools.FlatDataGridA();
            this.TitlesStatusBar = new FBITools.FlatStatusBarA();
            this.tblMainContent.SuspendLayout();
            this.tblInput.SuspendLayout();
            this.tblResult.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.TitlesGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // tblMainContent
            // 
            this.tblMainContent.ColumnCount = 1;
            this.tblMainContent.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblMainContent.Controls.Add(this.tblInput, 0, 0);
            this.tblMainContent.Controls.Add(this.tblResult, 0, 1);
            this.tblMainContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblMainContent.FillOnFormResize = true;
            this.tblMainContent.Location = new System.Drawing.Point(0, 0);
            this.tblMainContent.Name = "tblMainContent";
            this.tblMainContent.Padding = new System.Windows.Forms.Padding(1);
            this.tblMainContent.RowCount = 2;
            this.tblMainContent.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblMainContent.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblMainContent.Size = new System.Drawing.Size(704, 624);
            this.tblMainContent.SizeOriginal = new System.Drawing.Size(704, 624);
            this.tblMainContent.TabIndex = 0;
            // 
            // tblInput
            // 
            this.tblInput.ColumnCount = 3;
            this.tblInput.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tblInput.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tblInput.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tblInput.Controls.Add(this.lblTitle, 0, 0);
            this.tblInput.Controls.Add(this.TitleIDTextBox, 0, 1);
            this.tblInput.Controls.Add(this.txtTitleName, 0, 2);
            this.tblInput.Controls.Add(this.ListRegionCheckedList, 1, 1);
            this.tblInput.Controls.Add(this.ListCategoryCheckedList, 2, 1);
            this.tblInput.Controls.Add(this.GenerateCetkButton, 0, 3);
            this.tblInput.Controls.Add(this.WarningLabel, 0, 4);
            this.tblInput.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblInput.Location = new System.Drawing.Point(1, 1);
            this.tblInput.Name = "tblInput";
            this.tblInput.RowCount = 5;
            this.tblInput.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblInput.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblInput.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblInput.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblInput.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblInput.Size = new System.Drawing.Size(702, 194);
            this.tblInput.SizeOriginal = new System.Drawing.Size(702, 194);
            this.tblInput.TabIndex = 0;
            // 
            // lblTitle
            // 
            this.tblInput.SetColumnSpan(this.lblTitle, 3);
            this.lblTitle.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.lblTitle.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.lblTitle.Location = new System.Drawing.Point(0, 0);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(702, 34);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "WiiU cetk Generator";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // txtTitleID
            // 
            this.TitleIDTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleIDTextBox.LabelText = "Title ID";
            this.TitleIDTextBox.Location = new System.Drawing.Point(0, 38);
            this.TitleIDTextBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.TitleIDTextBox.Mask = App.Core.Desktop.TextMask.None;
            this.TitleIDTextBox.MaxLength = 16;
            this.TitleIDTextBox.Name = "txtTitleID";
            this.TitleIDTextBox.Size = new System.Drawing.Size(349, 34);
            this.TitleIDTextBox.TabIndex = 1;
            this.TitleIDTextBox.TextAlign = App.Core.Desktop.FlatMaskedTextBox.TextAlignTypes.Left;
            // 
            // txtTitleName
            // 
            this.txtTitleName.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.txtTitleName.LabelText = "Title Name";
            this.txtTitleName.Location = new System.Drawing.Point(0, 94);
            this.txtTitleName.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.txtTitleName.MaxLength = 0;
            this.txtTitleName.Name = "txtTitleName";
            this.txtTitleName.PreviousText = "";
            this.txtTitleName.Size = new System.Drawing.Size(349, 34);
            this.txtTitleName.TabIndex = 2;
            // 
            // chkListRegion
            // 
            this.ListRegionCheckedList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ListRegionCheckedList.Location = new System.Drawing.Point(353, 38);
            this.ListRegionCheckedList.Name = "chkListRegion";
            this.tblInput.SetRowSpan(this.ListRegionCheckedList, 2);
            this.ListRegionCheckedList.Size = new System.Drawing.Size(171, 90);
            this.ListRegionCheckedList.TabIndex = 3;
            this.ListRegionCheckedList.TextLegend = "Region";
            // 
            // chkListCategory
            // 
            this.ListCategoryCheckedList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ListCategoryCheckedList.Location = new System.Drawing.Point(528, 38);
            this.ListCategoryCheckedList.Name = "chkListCategory";
            this.tblInput.SetRowSpan(this.ListCategoryCheckedList, 2);
            this.ListCategoryCheckedList.Size = new System.Drawing.Size(172, 90);
            this.ListCategoryCheckedList.TabIndex = 4;
            this.ListCategoryCheckedList.TextLegend = "Category";
            // 
            // btnGenerateCetk
            // 
            this.tblInput.SetColumnSpan(this.GenerateCetkButton, 3);
            this.GenerateCetkButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.GenerateCetkButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.GenerateCetkButton.FlatAppearance.BorderSize = 0;
            this.GenerateCetkButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.GenerateCetkButton.Location = new System.Drawing.Point(0, 132);
            this.GenerateCetkButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.GenerateCetkButton.Name = "btnGenerateCetk";
            this.GenerateCetkButton.Size = new System.Drawing.Size(702, 34);
            this.GenerateCetkButton.TabIndex = 5;
            this.GenerateCetkButton.Text = "Generate cetk";
            // 
            // lblWarning
            // 
            this.tblInput.SetColumnSpan(this.WarningLabel, 3);
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.WarningLabel.Location = new System.Drawing.Point(0, 170);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.WarningLabel.Name = "lblWarning";
            this.WarningLabel.Size = new System.Drawing.Size(702, 24);
            this.WarningLabel.TabIndex = 6;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // tblResult
            // 
            this.tblResult.ColumnCount = 1;
            this.tblResult.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblResult.Controls.Add(this.TitlesGrid, 0, 0);
            this.tblResult.Controls.Add(this.TitlesStatusBar, 0, 1);
            this.tblResult.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tblResult.Location = new System.Drawing.Point(1, 195);
            this.tblResult.Name = "tblResult";
            this.tblResult.RowCount = 2;
            this.tblResult.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tblResult.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tblResult.Size = new System.Drawing.Size(702, 428);
            this.tblResult.SizeOriginal = new System.Drawing.Size(702, 428);
            this.tblResult.TabIndex = 1;
            // 
            // dgvTitles
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.TitlesGrid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.TitlesGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.TitlesGrid.ColorBackground = System.Drawing.Color.White;
            this.TitlesGrid.ColorColumnHeader = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            this.TitlesGrid.ColorColumnHeaderMouseHover = System.Drawing.Color.Empty;
            this.TitlesGrid.ColorColumnHeaderReorderDiv = System.Drawing.Color.Empty;
            this.TitlesGrid.ColorColumnHeaderReorderRec = System.Drawing.Color.Empty;
            this.TitlesGrid.ColorColumnSelection = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            this.TitlesGrid.ColorFontRow = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.TitlesGrid.ColorFontRowSelection = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.TitlesGrid.ColorGrid = System.Drawing.Color.Silver;
            this.TitlesGrid.ColorRow = System.Drawing.Color.White;
            this.TitlesGrid.ColorRowAlternate = System.Drawing.Color.White;
            this.TitlesGrid.ColorRowMouseHover = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(237)))), ((int)(((byte)(255)))));
            this.TitlesGrid.ColorRowSelection = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.TitlesGrid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.TitlesGrid.DefaultCellStyle = dataGridViewCellStyle3;
            this.TitlesGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitlesGrid.Location = new System.Drawing.Point(0, 2);
            this.TitlesGrid.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.TitlesGrid.Name = "dgvTitles";
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.TitlesGrid.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.TitlesGrid.RowTemplate.Height = 30;
            this.TitlesGrid.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.TitlesGrid.Size = new System.Drawing.Size(702, 397);
            this.TitlesGrid.StandardTab = true;
            this.TitlesGrid.TabIndex = 0;
            this.TitlesGrid.TabStop = true;
            // 
            // staTitles
            // 
            this.TitlesStatusBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(145)))), ((int)(((byte)(145)))));
            this.TitlesStatusBar.BackColorContent = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.TitlesStatusBar.BorderEnable = true;
            this.TitlesStatusBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.TitlesStatusBar.Location = new System.Drawing.Point(3, 402);
            this.TitlesStatusBar.Movimento = App.Core.Desktop.Movimento.Nenhum;
            this.TitlesStatusBar.Name = "staTitles";
            this.TitlesStatusBar.Registros = null;
            this.TitlesStatusBar.Size = new System.Drawing.Size(696, 23);
            this.TitlesStatusBar.TabIndex = 1;
            // 
            // WiiUcetkForm
            // 
            this.ClientSize = new System.Drawing.Size(704, 624);
            this.Controls.Add(this.tblMainContent);
            this.Name = "WiiUcetkForm";
            this.Text = "WiiUcetkForm";
            this.tblMainContent.ResumeLayout(false);
            this.tblMainContent.PerformLayout();
            this.tblInput.ResumeLayout(false);
            this.tblResult.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.TitlesGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatLabelA lblTitle;
        internal FlatMaskedTextBoxA TitleIDTextBox;
        private FlatTableLayoutPanelA tblMainContent;
        internal FlatButtonA GenerateCetkButton;
        internal FlatLabelA WarningLabel;
        internal FlatTableLayoutPanelA tblInput;
        private FlatTableLayoutPanelA tblResult;
        internal FlatTextBoxA txtTitleName;
        internal FlatDataGridA TitlesGrid;
        internal FlatCheckedListA ListRegionCheckedList;
        internal FlatCheckedListA ListCategoryCheckedList;
        internal FlatStatusBarA TitlesStatusBar;
    }
}