//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBITools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBITools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico_app {
            get {
                object obj = ResourceManager.GetObject("ico_app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  c.ID 
        ///	, c.Name 
        ///FROM Category AS c 
        ///WHERE 1 = 1 
        ///ORDER BY c.ID ASC;
        ///--.
        /// </summary>
        internal static string sql_WiiUCategory_List {
            get {
                return ResourceManager.GetString("sql_WiiUCategory_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  r.ID 
        ///	, r.Name 
        ///FROM Region AS r 
        ///WHERE 1 = 1 
        ///ORDER BY r.ID ASC;
        ///--.
        /// </summary>
        internal static string sql_WiiURegion_List {
            get {
                return ResourceManager.GetString("sql_WiiURegion_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///SELECT 
        ///	  UPPER(t.TitleID) AS TitleID 
        ///	, t.TitleKey 
        ///	, t.Name 
        ///	, t.Region 
        ///	, t.Category 
        ///FROM Title AS t 
        ///WHERE 1 = 1 
        ///ORDER BY t.TitleID ASC;
        ///--.
        /// </summary>
        internal static string sql_WiiUTitle_List {
            get {
                return ResourceManager.GetString("sql_WiiUTitle_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WiiUcetk {
            get {
                object obj = ResourceManager.GetObject("WiiUcetk", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
