// <auto-generated/>
namespace FBITools
{
    partial class WebCrawlerUI
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.MainContentTable = new FBITools.FlatTableA();
            this.InputTable = new FBITools.FlatTableA();
            this.TitleLabel = new FBITools.FlatLabelA();
            this.UrlTextBox = new FBITools.FlatMaskedTextBoxA();
            this.FolderTextBox = new FBITools.FlatTextBoxA();
            this.CrawButton = new FBITools.FlatButtonA();
            this.WarningLabel = new FBITools.FlatLabelA();
            this.ResultTable = new FBITools.FlatTableA();
            this.ResultGrid = new FBITools.FlatDataGridA();
            this.ResultStatusBar = new FBITools.FlatStatusBarA();
            this.Found = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.FileName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.FileSize = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.Date = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.MainContentTable.SuspendLayout();
            this.InputTable.SuspendLayout();
            this.ResultTable.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.ResultGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // MainContentTable
            // 
            this.MainContentTable.ColumnCount = 1;
            this.MainContentTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Controls.Add(this.InputTable, 0, 0);
            this.MainContentTable.Controls.Add(this.ResultTable, 0, 1);
            this.MainContentTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainContentTable.FillOnFormResize = true;
            this.MainContentTable.Location = new System.Drawing.Point(0, 0);
            this.MainContentTable.Name = "MainContentTable";
            this.MainContentTable.Padding = new System.Windows.Forms.Padding(1);
            this.MainContentTable.RowCount = 2;
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.MainContentTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.MainContentTable.Size = new System.Drawing.Size(704, 624);
            this.MainContentTable.SizeOriginal = new System.Drawing.Size(704, 624);
            this.MainContentTable.TabIndex = 0;
            // 
            // InputTable
            // 
            this.InputTable.ColumnCount = 3;
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.InputTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.InputTable.Controls.Add(this.TitleLabel, 0, 0);
            this.InputTable.Controls.Add(this.UrlTextBox, 0, 1);
            this.InputTable.Controls.Add(this.FolderTextBox, 0, 2);
            this.InputTable.Controls.Add(this.CrawButton, 0, 3);
            this.InputTable.Controls.Add(this.WarningLabel, 0, 4);
            this.InputTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.InputTable.Location = new System.Drawing.Point(1, 1);
            this.InputTable.Name = "InputTable";
            this.InputTable.RowCount = 5;
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.InputTable.Size = new System.Drawing.Size(702, 176);
            this.InputTable.SizeOriginal = new System.Drawing.Size(702, 176);
            this.InputTable.TabIndex = 0;
            // 
            // TitleLabel
            // 
            this.InputTable.SetColumnSpan(this.TitleLabel, 3);
            this.TitleLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.TitleLabel.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.TitleLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.TitleLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.TitleLabel.Location = new System.Drawing.Point(0, 0);
            this.TitleLabel.Margin = new System.Windows.Forms.Padding(0, 0, 0, 2);
            this.TitleLabel.Name = "TitleLabel";
            this.TitleLabel.Size = new System.Drawing.Size(702, 34);
            this.TitleLabel.TabIndex = 0;
            this.TitleLabel.Text = "WebCrawler";
            this.TitleLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // UrlTextBox
            // 
            this.UrlTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UrlTextBox.LabelText = "URL";
            this.UrlTextBox.Location = new System.Drawing.Point(0, 38);
            this.UrlTextBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.UrlTextBox.Mask = App.Core.Desktop.TextMask.None;
            this.UrlTextBox.MaxLength = 16;
            this.UrlTextBox.Name = "UrlTextBox";
            this.UrlTextBox.Size = new System.Drawing.Size(349, 34);
            this.UrlTextBox.TabIndex = 1;
            this.UrlTextBox.TextAlign = App.Core.Desktop.FlatMaskedTextBox.TextAlignTypes.Left;
            // 
            // FolderTextBox
            // 
            this.FolderTextBox.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.FolderTextBox.LabelText = "Folder";
            this.FolderTextBox.Location = new System.Drawing.Point(0, 76);
            this.FolderTextBox.Margin = new System.Windows.Forms.Padding(0, 2, 2, 2);
            this.FolderTextBox.MaxLength = 0;
            this.FolderTextBox.Name = "FolderTextBox";
            this.FolderTextBox.PreviousText = "";
            this.FolderTextBox.Size = new System.Drawing.Size(349, 34);
            this.FolderTextBox.TabIndex = 2;
            // 
            // CrawButton
            // 
            this.CrawButton.BorderColorDefault = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.InputTable.SetColumnSpan(this.CrawButton, 3);
            this.CrawButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CrawButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(223)))), ((int)(((byte)(229)))));
            this.CrawButton.FlatAppearance.BorderSize = 0;
            this.CrawButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(213)))), ((int)(((byte)(213)))));
            this.CrawButton.Location = new System.Drawing.Point(0, 114);
            this.CrawButton.Margin = new System.Windows.Forms.Padding(0, 2, 0, 2);
            this.CrawButton.Name = "CrawButton";
            this.CrawButton.Size = new System.Drawing.Size(702, 34);
            this.CrawButton.TabIndex = 3;
            this.CrawButton.Text = "Craw";
            // 
            // WarningLabel
            // 
            this.InputTable.SetColumnSpan(this.WarningLabel, 3);
            this.WarningLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WarningLabel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(149)))), ((int)(((byte)(237)))));
            this.WarningLabel.ForeColorType = App.Core.Desktop.LabelType.primary;
            this.WarningLabel.Location = new System.Drawing.Point(0, 152);
            this.WarningLabel.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.WarningLabel.Name = "WarningLabel";
            this.WarningLabel.Size = new System.Drawing.Size(702, 24);
            this.WarningLabel.TabIndex = 4;
            this.WarningLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // ResultTable
            // 
            this.ResultTable.ColumnCount = 1;
            this.ResultTable.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.Controls.Add(this.ResultGrid, 0, 0);
            this.ResultTable.Controls.Add(this.ResultStatusBar, 0, 1);
            this.ResultTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResultTable.Location = new System.Drawing.Point(1, 177);
            this.ResultTable.Name = "ResultTable";
            this.ResultTable.RowCount = 2;
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.ResultTable.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.ResultTable.Size = new System.Drawing.Size(702, 446);
            this.ResultTable.SizeOriginal = new System.Drawing.Size(702, 446);
            this.ResultTable.TabIndex = 1;
            // 
            // ResultGrid
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.White;
            this.ResultGrid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.ResultGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.ResultGrid.ColorBackground = System.Drawing.Color.White;
            this.ResultGrid.ColorColumnHeader = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            this.ResultGrid.ColorColumnHeaderMouseHover = System.Drawing.Color.Empty;
            this.ResultGrid.ColorColumnHeaderReorderDiv = System.Drawing.Color.Empty;
            this.ResultGrid.ColorColumnHeaderReorderRec = System.Drawing.Color.Empty;
            this.ResultGrid.ColorColumnSelection = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            this.ResultGrid.ColorFontRow = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ResultGrid.ColorFontRowSelection = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ResultGrid.ColorGrid = System.Drawing.Color.Silver;
            this.ResultGrid.ColorRow = System.Drawing.Color.White;
            this.ResultGrid.ColorRowAlternate = System.Drawing.Color.White;
            this.ResultGrid.ColorRowMouseHover = System.Drawing.Color.FromArgb(((int)(((byte)(189)))), ((int)(((byte)(237)))), ((int)(((byte)(255)))));
            this.ResultGrid.ColorRowSelection = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(132)))), ((int)(((byte)(199)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.ResultGrid.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.ResultGrid.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.Found,
            this.FileName,
            this.FileSize,
            this.Date});
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(229)))), ((int)(((byte)(226)))), ((int)(((byte)(244)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.ResultGrid.DefaultCellStyle = dataGridViewCellStyle4;
            this.ResultGrid.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ResultGrid.Location = new System.Drawing.Point(0, 2);
            this.ResultGrid.Margin = new System.Windows.Forms.Padding(0, 2, 0, 0);
            this.ResultGrid.MultiSelect = true;
            this.ResultGrid.Name = "ResultGrid";
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.ResultGrid.RowHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.ResultGrid.RowTemplate.Height = 30;
            this.ResultGrid.RowTemplate.Resizable = System.Windows.Forms.DataGridViewTriState.False;
            this.ResultGrid.Size = new System.Drawing.Size(702, 415);
            this.ResultGrid.StandardTab = true;
            this.ResultGrid.TabIndex = 0;
            this.ResultGrid.TabStop = true;
            // 
            // ResultStatusBar
            // 
            this.ResultStatusBar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(145)))), ((int)(((byte)(145)))));
            this.ResultStatusBar.BackColorContent = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.ResultStatusBar.BorderEnable = true;
            this.ResultStatusBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.ResultStatusBar.Location = new System.Drawing.Point(3, 420);
            this.ResultStatusBar.Movimento = App.Core.Desktop.Movimento.Nenhum;
            this.ResultStatusBar.Name = "ResultStatusBar";
            this.ResultStatusBar.Registros = null;
            this.ResultStatusBar.Size = new System.Drawing.Size(696, 23);
            this.ResultStatusBar.TabIndex = 1;
            // 
            // Found
            // 
            this.Found.DataPropertyName = "Found";
            this.Found.HeaderText = "Found";
            this.Found.Name = "Found";
            this.Found.ReadOnly = true;
            // 
            // FileName
            // 
            this.FileName.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.AllCells;
            this.FileName.DataPropertyName = "FileName";
            this.FileName.HeaderText = "FileName";
            this.FileName.Name = "FileName";
            this.FileName.ReadOnly = true;
            this.FileName.Width = 81;
            // 
            // FileSize
            // 
            this.FileSize.DataPropertyName = "FileSize";
            this.FileSize.HeaderText = "FileSize";
            this.FileSize.Name = "FileSize";
            this.FileSize.ReadOnly = true;
            // 
            // Date
            // 
            this.Date.DataPropertyName = "Date";
            dataGridViewCellStyle3.Format = "dd-MMM-yyyy HH:mm";
            dataGridViewCellStyle3.NullValue = null;
            this.Date.DefaultCellStyle = dataGridViewCellStyle3;
            this.Date.HeaderText = "Date";
            this.Date.Name = "Date";
            this.Date.ReadOnly = true;
            // 
            // WebCrawlerUI
            // 
            this.ClientSize = new System.Drawing.Size(704, 624);
            this.Controls.Add(this.MainContentTable);
            this.Name = "WebCrawlerUI";
            this.SizeOriginal = new System.Drawing.Size(430, 262);
            this.Text = "WiiUcetkForm";
            this.MainContentTable.ResumeLayout(false);
            this.MainContentTable.PerformLayout();
            this.InputTable.ResumeLayout(false);
            this.ResultTable.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.ResultGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private FlatLabelA TitleLabel;
        internal FlatMaskedTextBoxA UrlTextBox;
        private FlatTableA MainContentTable;
        internal FlatButtonA CrawButton;
        internal FlatLabelA WarningLabel;
        private FlatTableA ResultTable;
        internal FlatTextBoxA FolderTextBox;
        internal FlatDataGridA ResultGrid;
        internal FlatStatusBarA ResultStatusBar;
        private FlatTableA InputTable;
        private System.Windows.Forms.DataGridViewTextBoxColumn Found;
        private System.Windows.Forms.DataGridViewTextBoxColumn FileName;
        private System.Windows.Forms.DataGridViewTextBoxColumn FileSize;
        private System.Windows.Forms.DataGridViewTextBoxColumn Date;
    }
}